---
###############################################################################
#
# cron_present.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - iac_cron is defined
    fail_msg: "All tests did not pass"

###############################################################################
# LOOPING THROUGH CRONJOBS
###############################################################################

- name: "Looping through cronjobs"
  ansible.builtin.cron:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    user: "{{ item.user | default('root') }}"
    weekday: "{{ item.weekday | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    job: "{{ item.job }}"
    cron_file: "{{ item.cron_file }}"
  loop: "{{ iac_cron | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
