---
###############################################################################
#
# reloaded.yml
#
# @author Arsi Atomi
#
###############################################################################

- name: "Ensuring firewalld rules are reloaded"
  ansible.builtin.command: >
    firewall-cmd --reload
  register: my_output
  changed_when: my_output.rc != 0
