---
###############################################################################
#
# stopped.yml
#
# @author Arsi Atomi
#
###############################################################################

- name: "Ensuring firewalld is stopped"
  ansible.builtin.systemd_service:
    name: firewalld
    state: stopped
